# docker-compose.build.yml
# Used for building and pushing images to Docker Hub
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      platform: linux/arm64
      args:
        DOCKER_BUILDKIT: 1
    image: ${DOCKERHUB_USERNAME}/airbrush-web-frontend:latest

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      platform: linux/arm64
      args:
        DOCKER_BUILDKIT: 1
    image: ${DOCKERHUB_USERNAME}/airbrush-web-backend:latest
    depends_on:
      - frontend
    volumes:
      - airbrush-web-data:/data

volumes:
  airbrush-web-data:
